# -*- coding: utf-8 -*-
"""fakenewsdetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6bt2TUmLdLWzhFBfbz5-yrV481ENxIF
"""

# Only run once; ensures latest compatible versions for Python 3.12
!pip install --quiet torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
!pip install --quiet transformers tensorflow keras pandas numpy matplotlib seaborn scikit-learn nltk wordcloud

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay

from wordcloud import WordCloud

# TensorFlow / Keras for LSTM
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

# PyTorch + Transformers for BERT
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Replace paths with your files
import pandas as pd
df_true = pd.read_csv(r'/True.csv')
df_fake = pd.read_csv(r'/Fake.csv')

df_true['label'] = 'REAL'
df_fake['label'] = 'FAKE'

df_true = df_true[['text','label']]
df_fake = df_fake[['text','label']]

# Combine datasets
df = pd.concat([df_true, df_fake], ignore_index=True)
df = df.dropna(subset=['text'])
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df.head()

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text

df['clean_text'] = df['text'].apply(clean_text)

le = LabelEncoder()
df['label_enc'] = le.fit_transform(df['label'])  # FAKE=1, REAL=0

X = df['clean_text']
y = df['label_enc']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

lr = LogisticRegression()
lr.fit(X_train_tfidf, y_train)
y_pred_lr = lr.predict(X_test_tfidf)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))
ConfusionMatrixDisplay.from_estimator(lr, X_test_tfidf, y_test)
plt.show()

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train_tfidf, y_train)
y_pred_rf = rf.predict(X_test_tfidf)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

# Top 10 important words
importances = rf.feature_importances_
indices = np.argsort(importances)[-10:]
features = tfidf.get_feature_names_out()

plt.figure(figsize=(10,5))
plt.barh(range(10), importances[indices], align='center')
plt.yticks(range(10), [features[i] for i in indices])
plt.title("Top 10 Important Words (Random Forest)")
plt.show()

tokenizer_dl = Tokenizer(num_words=5000)
tokenizer_dl.fit_on_texts(X_train)

X_train_seq = tokenizer_dl.texts_to_sequences(X_train)
X_test_seq = tokenizer_dl.texts_to_sequences(X_test)

max_len = 200
X_train_pad = pad_sequences(X_train_seq, maxlen=max_len)
X_test_pad = pad_sequences(X_test_seq, maxlen=max_len)

model_lstm = Sequential([
    Embedding(input_dim=5000, output_dim=128, input_length=max_len),
    LSTM(128, dropout=0.2, recurrent_dropout=0.2),
    Dense(1, activation='sigmoid')
])

model_lstm.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
history_lstm = model_lstm.fit(X_train_pad, y_train, epochs=3, batch_size=64, validation_split=0.1)

score_lstm = model_lstm.evaluate(X_test_pad, y_test)
print("LSTM Test Accuracy:", score_lstm[1])

tokenizer_bert = AutoTokenizer.from_pretrained("bert-base-uncased")
bert_model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased", num_labels=2
).to(device)

def encode_bert(texts, max_len=128):
    return tokenizer_bert(
        list(texts),
        padding='max_length',
        truncation=True,
        max_length=max_len,
        return_tensors='pt'
    ).to(device)

# Sample BERT inference
sample_text = ["Breaking news: Aliens discovered on Mars!"]
inputs = encode_bert(sample_text)
with torch.no_grad():
    outputs = bert_model(**inputs)
pred_label = torch.argmax(outputs.logits, dim=1).item()
print("BERT Prediction:", "Fake" if pred_label==1 else "Real")

fake = df[df['label']=='FAKE']['text']
real = df[df['label']=='REAL']['text']

wc_fake = WordCloud(width=800, height=400, background_color='white').generate(' '.join(fake))
wc_real = WordCloud(width=800, height=400, background_color='white').generate(' '.join(real))

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.imshow(wc_fake, interpolation='bilinear')
plt.axis('off')
plt.title("Fake News WordCloud")
plt.subplot(1,2,2)
plt.imshow(wc_real, interpolation='bilinear')
plt.axis('off')
plt.title("Real News WordCloud")
plt.show()
